### ISSUE TITLE
help with reading binary data from buffer

### ISSUE THREAD

**Issue by ORESoftware** [dodekeract/bitwise#2]
I have this question on SO:

http://stackoverflow.com/questions/41715421/read-binary-data-from-buffer

I am wondering if this library can help. pretty unsure of how to proceed.

**Comment by dodekeract** [comment]
The answer you got `buf[0] > 127` should work as "first bit is 1" means that the number is at least 128 big. That's what the answer is testing for.

Alternatively you can also just use `buf[0] & 128 === 128` which would only be true if the first bit is 1.

If you want to use `bitwise`, you should be able to just do this:

```
var bitwise = require('bitwise')
var array = bitwise.readBuffer(buffer, 7, 1) // read 1 bit skipping the first 7 bits
```

`array` should then be either `[0]` or `[1]` as `bitwise.readBuffer` returns an array of {0,1}.

**Comment by dodekeract** [comment]
Let me know if you still have issues.
