### ISSUE TITLE
did you remove .toBits?

### ISSUE THREAD

**Issue by dkebler** [dodekeract/bitwise#4]
while upgrading packages in my utility library it throws error for missing .toBits function.
can you please put it back.  Thx

https://github.com/dodekeract/bitwise/tree/master/source/bits

**Comment by dkebler** [comment]
```
/**
 *	Converts a string into an array of bits. Ignores all characters except 1 and 0.
 *
 *	@example
 *	toBits('10 10 12$%_.0') => [1,0,1,0,1,0]
 *
 *	@param string {String} the string to convert
 *	@return {Array}
 */
function toBits (string) {
	var arr = [];
	var index = 0;
	for (var i = 0; i < string.length; i++) {
		if (string[i] === '1') {
			arr[index] = 1;
			index++;
		} else if (string[i] === '0') {
			arr[index] = 0;
			index++;
		}
	}

	return arr;
}
```

**Comment by dkebler** [comment]
don't know when you removed this probably when you refactored in 2018 to the bits file.  I had to go back to last 2016 commit to find it.

**Comment by dkebler** [comment]
hold on for PR

**Comment by dkebler** [comment]
#5 

Bitwise turn out to be a critical module to my whole IOT MCP library so hoping there are not other breaking changes.  So guess I just have to revert to < 1.0 until this is merged at least.  Thx

**Comment by dodekeract** [comment]
Hi @dkebler, sorry for breaking your workflow. Yes, the refactor was breaking, but that's why I bumped the major version (`1.0.0`).

I appreciate your Pull Request, but I actually didn't remove the `.toBits` function. Since the library got a lot more functionality, I decided to namespace all features, so the function you're looking for should be here:

```js
import bitwise from 'bitwise'
bitwise.string.toBits()

// or

import toBits from 'bitwise/string/to-bits'
toBits()

// or

const bitwise = require('bitwise').default
bitwise.string.toBits()

// or

const toBits = require('bitwise/string/to-bits').default
toBits()
```

I can see why that's confusing if you're used to the old API, but I think it makes the whole thing a bit easier to grasp/maintain. Previously, you didn't really have a way to tell that it converted a string to bits. It may have been something else. Now, it's pretty clear what's happening:

```js
`bitwise.${whatYouHave}.${whatYouWant}`
// e.g.
`bitwise.${I have a string}.${I want bits}`
// => bitwise.string.toBits()
```

Glad to see that this library is actually used somewhere though. 😉

Let me know if this solves the issue for you and if you can upgrade to `1.x` now.

**Comment by dkebler** [comment]
ok, yea I didn't see it in the string folder :-).  Just assumed it was in bits folder.

Yes it is a VERY useful library for talking to an MCP gpio expander chip cause you can only write an entire byte (8 pins) at once thus if you want to for example toggle just one pin of 8 you need to do some bitwise :-). operations first.

other than moving things around did you know off hand any functions that you changed the actual arguments or functionality and thus I should be on the lookout?

-------------------
btw I faced the same namespace issue with my utility library.  I added a merge feature to require_dir that "flattened" all the props, but still lets users choose a specific folder to import.  Of course if you have duplicate names merging will overwrite one of them :-).  Still makes it nice not to have to do an extra .namespace all the time or import them separately.   Unfortunately I can't do with with esm yet because the import() function is not available at least not native node 9+.

I want to adopt you new shiny model but will need to stop what I am doing and look carefully at my "byte" utility module for your namespace changes.  When I do I'll let you know.  
https://github.com/uCOMmandIt/uci-utils/blob/master/src/byte.js

You might consider adopting some of my byte module.  It has a byte class that hold a current and previous value and that you can set to one of several formats.  ['STR', 'BUF', 'DEC', 'HEX', 'ARY', 'PLC'] .   It makes it easy to convert one to another and has several bitwise operations as methods based on 'bitwise'.  You "push" new byte on any time and then you can check for bitwise state change for example.   PLC is my favorite.   It's just an array numbers 1-8 of which bits are set.  Makes it easy to 'translate' from the "real world" request to turn on a pin to the actual decimal code that must be sent to the mcp chip via the i2cbus. 

So yea big thx.

**Comment by dodekeract** [comment]
@dkebler I'm not entirely sure if it's the only thing, but `bitwise@1` actually `throw`s errors when you pass invalid data, so you can find issues faster.

Most of the APIs you used should be basically untouched, besides modernizing/structuring them.

Your project is also the first project I saw that utilizes a big part of this library. Most people only use `readByte`/`writeByte` AFAIK.

> if you want to toggle bits

I actually added that feature, you can now just read/write/toggle a single bit. Should be in the `integer` section.

> you should adapt a part of byte

Yes, I thought about doing something similar, not sure if I find the time for it though as I'm pretty busy with work. Gotta get as much money as possible before @iotaledger goes mainstream. 🤫
